<?php

use Illuminate\Database\Seeder;

class BarrioSeeder extends Seeder
{
    
    // php artisan db:seed --class=UsuarioSeeder

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('barrio')->insert([
            ['co_barrio' =>	1	, 'nb_barrio' => 'Barrio Alto Aguacatal' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	2	, 'nb_barrio' => 'Barrio Bajo Aguacatal' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	3	, 'nb_barrio' => 'Barrio la Legua' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	4	, 'nb_barrio' => 'Barrio Palmas I' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	5	, 'nb_barrio' => 'Barrio Palmas II' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	6	, 'nb_barrio' => 'Barrio Terrón Colorado I' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	7	, 'nb_barrio' => 'Barrio Terrón Colorado II' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	8	, 'nb_barrio' => 'Barrio Villa del Mar' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	9	, 'nb_barrio' => 'El Barrio Bajo Palermo' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	10	, 'nb_barrio' => 'El barrio Vista hermosa' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	11	, 'nb_barrio' => 'Urbanización Aguacatal' , 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	12	, 'nb_barrio' => 'Altos de Menga' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	13	, 'nb_barrio' => 'Arboledas' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	14	, 'nb_barrio' => 'Área Libre-Parque del Amor' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	15	, 'nb_barrio' => 'Arroyohondo' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	16	, 'nb_barrio' => 'Brisas de los Álamos' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	17	, 'nb_barrio' => 'Centenario' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	18	, 'nb_barrio' => 'Chipichape' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	19	, 'nb_barrio' => 'Ciudad los Álamos' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	20	, 'nb_barrio' => 'Dapa' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	21	, 'nb_barrio' => 'El Bosque' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	22	, 'nb_barrio' => 'Granada' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	23	, 'nb_barrio' => 'Juanambú' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	24	, 'nb_barrio' => 'La Campiña' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	25	, 'nb_barrio' => 'La Flora' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	26	, 'nb_barrio' => 'La Paz' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	27	, 'nb_barrio' => 'Menga' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	28	, 'nb_barrio' => 'Normandía' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	29	, 'nb_barrio' => 'Pacará' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	30	, 'nb_barrio' => 'Prados del Norte' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	31	, 'nb_barrio' => 'San Vicente' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	32	, 'nb_barrio' => 'Santa Mónica' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	33	, 'nb_barrio' => 'Santa Rita' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	34	, 'nb_barrio' => 'Santa Teresita' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	35	, 'nb_barrio' => 'Sect Altos Normandía-Bataclán' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	36	, 'nb_barrio' => 'Urbanización La Flora' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	37	, 'nb_barrio' => 'Urbanización La Merced' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	38	, 'nb_barrio' => 'Versalles' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	39	, 'nb_barrio' => 'Vipasa' , 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	40	, 'nb_barrio' => 'Acueducto San Antonio.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	41	, 'nb_barrio' => 'El Calvario.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	42	, 'nb_barrio' => 'El Hoyo.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	43	, 'nb_barrio' => 'El Nacional.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	44	, 'nb_barrio' => 'El Peñón.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	45	, 'nb_barrio' => 'El Piloto.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	46	, 'nb_barrio' => 'La Merced.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	47	, 'nb_barrio' => 'Los Libertadores.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	48	, 'nb_barrio' => 'Navarro-La Chanca.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	49	, 'nb_barrio' => 'San Antonio.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	50	, 'nb_barrio' => 'San Cayetano.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	51	, 'nb_barrio' => 'San Juan Bosco.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	52	, 'nb_barrio' => 'San Nicolás.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	53	, 'nb_barrio' => 'San Pascual.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	54	, 'nb_barrio' => 'San Pedro.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	55	, 'nb_barrio' => 'Santa Rosa.' , 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	56	, 'nb_barrio' => 'Bolivariano' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	57	, 'nb_barrio' => 'Bueno Madrid' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	58	, 'nb_barrio' => 'Calima' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	59	, 'nb_barrio' => 'Evaristo García' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	60	, 'nb_barrio' => 'Fátima' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	61	, 'nb_barrio' => 'Flora Industrial' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	62	, 'nb_barrio' => 'Guillermo Valencia' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	63	, 'nb_barrio' => 'Ignacio Rengifo' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	64	, 'nb_barrio' => 'Industria de Licores' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	65	, 'nb_barrio' => 'Jorge Isaacs' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	66	, 'nb_barrio' => 'La Alianza' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	67	, 'nb_barrio' => 'La Esmeralda' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	68	, 'nb_barrio' => 'La Isla' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	69	, 'nb_barrio' => 'Las Delicias' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	70	, 'nb_barrio' => 'Manzanares' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	71	, 'nb_barrio' => 'Marco Fidel Suárez' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	72	, 'nb_barrio' => 'Olaya Herrera' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	73	, 'nb_barrio' => 'Popular' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	74	, 'nb_barrio' => 'Porvenir' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	75	, 'nb_barrio' => 'Salomia' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	76	, 'nb_barrio' => 'Santander' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	77	, 'nb_barrio' => 'Sultana-Berlín-San Francisco' , 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	78	, 'nb_barrio' => 'Bajo Salomia' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	79	, 'nb_barrio' => 'Barrio Residencial el Bosque' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	80	, 'nb_barrio' => 'Brisas de los Andes' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	81	, 'nb_barrio' => 'Brisas del Guabito' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	82	, 'nb_barrio' => 'Chiminangos 1.ª Etapa' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	83	, 'nb_barrio' => 'Chiminangos 2.ª Etapa' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	84	, 'nb_barrio' => 'El Sena' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	85	, 'nb_barrio' => 'La Rivera II' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	86	, 'nb_barrio' => 'Los Andes' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	87	, 'nb_barrio' => 'Los Guayacanes' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	88	, 'nb_barrio' => 'Metropolitano del Norte' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	89	, 'nb_barrio' => 'Palmeras del norte' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	90	, 'nb_barrio' => 'Paseo de los Almendros' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	91	, 'nb_barrio' => 'Plazas Verdes' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	92	, 'nb_barrio' => 'Santa Bárbara' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	93	, 'nb_barrio' => 'Torres de Comfandi' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	94	, 'nb_barrio' => 'Urbanización Barranquilla' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	95	, 'nb_barrio' => 'Villa del Prado' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	96	, 'nb_barrio' => 'Villa del Sol' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	97	, 'nb_barrio' => 'Villas de Veracruz' , 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	98	, 'nb_barrio' => 'Álamos' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	99	, 'nb_barrio' => 'Calimio' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	100	, 'nb_barrio' => 'FloraliaI' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	101	, 'nb_barrio' => 'FloraliaI Sector II' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	102	, 'nb_barrio' => 'FloraliaIA' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	103	, 'nb_barrio' => 'FloraliaII' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	104	, 'nb_barrio' => 'FloraliaIII' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	105	, 'nb_barrio' => 'Fonaviemcali' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	106	, 'nb_barrio' => 'Jorge Eliécer Gaitán' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	107	, 'nb_barrio' => 'La Rivera I' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	108	, 'nb_barrio' => 'Los Alcázares I' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	109	, 'nb_barrio' => 'Los Alcázares II' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	110	, 'nb_barrio' => 'Los Guadales' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	111	, 'nb_barrio' => 'oasis de comfandi' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	112	, 'nb_barrio' => 'Paso del Comercio' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	113	, 'nb_barrio' => 'PetecuyI etapa' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	114	, 'nb_barrio' => 'PetecuyII etapa' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	115	, 'nb_barrio' => 'PetecuyIII etapa' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	116	, 'nb_barrio' => 'popular' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	117	, 'nb_barrio' => 'San Luís I' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	118	, 'nb_barrio' => 'San Luís II' , 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	119	, 'nb_barrio' => 'Alfonzo López 1.ª Etapa.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	120	, 'nb_barrio' => 'Alfonzo López 2.ª Etapa.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	121	, 'nb_barrio' => 'Alfonzo López 3.ª Etapa.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	122	, 'nb_barrio' => 'Andrés Sanin.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	123	, 'nb_barrio' => 'Base Aérea.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	124	, 'nb_barrio' => 'El Vivero' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	125	, 'nb_barrio' => 'Fepicol.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	126	, 'nb_barrio' => 'La Playa.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	127	, 'nb_barrio' => 'Las Ceibas.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	128	, 'nb_barrio' => 'Las Veraneras.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	129	, 'nb_barrio' => 'Los Pinos.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	130	, 'nb_barrio' => 'Puerto Mallarino.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	131	, 'nb_barrio' => 'Puerto Nuevo.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	132	, 'nb_barrio' => 'San Marino.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	133	, 'nb_barrio' => 'Siete de Agosto.' , 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	134	, 'nb_barrio' => 'Atanasio Girardot' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	135	, 'nb_barrio' => 'Benjamín Herrera' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	136	, 'nb_barrio' => 'Chapinero' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	137	, 'nb_barrio' => 'El trébol' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	138	, 'nb_barrio' => 'El troncal' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	139	, 'nb_barrio' => 'Industrial' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	140	, 'nb_barrio' => 'La Base' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	141	, 'nb_barrio' => 'La Floresta' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	142	, 'nb_barrio' => 'La Nueva Base' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	143	, 'nb_barrio' => 'Las Américas' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	144	, 'nb_barrio' => 'Municipal' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	145	, 'nb_barrio' => 'Primitivo Crespo' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	146	, 'nb_barrio' => 'Rafael Uribe Uribe' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	147	, 'nb_barrio' => 'Saavedra Galindo' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	148	, 'nb_barrio' => 'Santa Fe' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	149	, 'nb_barrio' => 'Santa Mónica Popular' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	150	, 'nb_barrio' => 'Simón Bolívar' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	151	, 'nb_barrio' => 'Urbanización La Base' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	152	, 'nb_barrio' => 'Villacolombia' , 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	153	, 'nb_barrio' => 'Alameda' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	154	, 'nb_barrio' => 'Aranjuez' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	155	, 'nb_barrio' => 'Belalcázar' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	156	, 'nb_barrio' => 'Bretaña' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	157	, 'nb_barrio' => 'Guayaquil' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	158	, 'nb_barrio' => 'Junín' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	159	, 'nb_barrio' => 'Manuel María Buenaventura' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	160	, 'nb_barrio' => 'Obrero' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	161	, 'nb_barrio' => 'Santa Mónica Belalcázar' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	162	, 'nb_barrio' => 'Sector La Luna' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	163	, 'nb_barrio' => 'Sucre' , 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	164	, 'nb_barrio' => 'Colseguros Andes' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	165	, 'nb_barrio' => 'Cristóbal Colon' , 'id_comuna' =>	10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	166	, 'nb_barrio' => 'Departamental' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	167	, 'nb_barrio' => 'El Dorado' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	168	, 'nb_barrio' => 'Guabal' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	169	, 'nb_barrio' => 'Jorge Zawadsky' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	170	, 'nb_barrio' => 'La Libertad' , 'id_comuna' =>	10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	171	, 'nb_barrio' => 'La Selva' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	172	, 'nb_barrio' => 'Las Acacias' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	173	, 'nb_barrio' => 'Las Granjas' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	174	, 'nb_barrio' => 'Olímpico' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	175	, 'nb_barrio' => 'Panamericano' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	176	, 'nb_barrio' => 'Pasamacho' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	177	, 'nb_barrio' => 'San Cristóbal' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	178	, 'nb_barrio' => 'San Judas Tadeo 1' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	179	, 'nb_barrio' => 'San Judas Tadeo 2' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	180	, 'nb_barrio' => 'Santa Elena' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	181	, 'nb_barrio' => 'Santo Domingo' , 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	182	, 'nb_barrio' => '20 de julio' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	183	, 'nb_barrio' => 'Agua blanca' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	184	, 'nb_barrio' => 'Ciudad Modelo' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	185	, 'nb_barrio' => 'El jardín' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	186	, 'nb_barrio' => 'El prado' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	187	, 'nb_barrio' => 'El recuerdo' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	188	, 'nb_barrio' => 'José Holguín Garcés' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	189	, 'nb_barrio' => 'JoseMaría Córdoba' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	190	, 'nb_barrio' => 'La Esperanza' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	191	, 'nb_barrio' => 'La Fortaleza' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	192	, 'nb_barrio' => 'La Independencia' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	193	, 'nb_barrio' => 'La Primavera' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	194	, 'nb_barrio' => 'León XIII' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	195	, 'nb_barrio' => 'Los Conquistadores' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	196	, 'nb_barrio' => 'Los Sauces' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	197	, 'nb_barrio' => 'Maracaibo' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	198	, 'nb_barrio' => 'Prados de Oriente' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	199	, 'nb_barrio' => 'San Benito' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	200	, 'nb_barrio' => 'San Carlos' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	201	, 'nb_barrio' => 'San Pedro Claver' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	202	, 'nb_barrio' => 'Urbanización Boyacá' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	203	, 'nb_barrio' => 'Villa del Sur' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	204	, 'nb_barrio' => 'villa nueva' , 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	205	, 'nb_barrio' => 'Alfonso Barberena' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	206	, 'nb_barrio' => 'Asturias' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	207	, 'nb_barrio' => 'Bello Horizonte' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	208	, 'nb_barrio' => 'Doce de Octubre' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	209	, 'nb_barrio' => 'Eduardo Santos' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	210	, 'nb_barrio' => 'El Paraíso' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	211	, 'nb_barrio' => 'FenalcoKennedy' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	212	, 'nb_barrio' => 'Julio Rincon' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	213	, 'nb_barrio' => 'Nueva Floresta' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	214	, 'nb_barrio' => 'Rodeo' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	215	, 'nb_barrio' => 'Sindical' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	216	, 'nb_barrio' => 'Villanueva' , 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	217	, 'nb_barrio' => 'Calipso' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	218	, 'nb_barrio' => 'Charco Azul' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	219	, 'nb_barrio' => 'El Diamante' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	220	, 'nb_barrio' => 'El Poblado I' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	221	, 'nb_barrio' => 'El Poblado II' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	222	, 'nb_barrio' => 'El Pondaje' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	223	, 'nb_barrio' => 'El Vergel' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	224	, 'nb_barrio' => 'La Paz' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	225	, 'nb_barrio' => 'Lleras Restrepo' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	226	, 'nb_barrio' => 'Lleras-Cinta larga' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	227	, 'nb_barrio' => 'Los Comuneros II' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	228	, 'nb_barrio' => 'Los Lagos I' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	229	, 'nb_barrio' => 'Los Lagos II' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	230	, 'nb_barrio' => 'Los Robles' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	231	, 'nb_barrio' => 'Marroquín III' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	232	, 'nb_barrio' => 'Nuevo Horizonte' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	233	, 'nb_barrio' => 'Omar Torrijos' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	234	, 'nb_barrio' => 'Ricardo Balcázar' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	235	, 'nb_barrio' => 'Rodrigo Lara Bonilla' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	236	, 'nb_barrio' => 'Sector Asprosocial–Diamante' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	237	, 'nb_barrio' => 'Sector Laguna del Pondaje' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	238	, 'nb_barrio' => 'Ulpiano Lloreda' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	239	, 'nb_barrio' => 'Villa Blanca' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	240	, 'nb_barrio' => 'Villa del Lago' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	241	, 'nb_barrio' => 'Yira Castro' , 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	242	, 'nb_barrio' => 'Alfonso Bonilla Aragon' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	243	, 'nb_barrio' => 'Alirio Mora Beltrán' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	244	, 'nb_barrio' => 'José Manuel Marroquín 1' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	245	, 'nb_barrio' => 'José Manuel Marroquín 2' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	246	, 'nb_barrio' => 'Las Orquídeas' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	247	, 'nb_barrio' => 'Manuela Beltrán' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	248	, 'nb_barrio' => 'Naranjos 1' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	249	, 'nb_barrio' => 'Naranjos 2' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	250	, 'nb_barrio' => 'Promociones Populares' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	251	, 'nb_barrio' => 'Puertas del Sol' , 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	252	, 'nb_barrio' => 'Bajos de Ciudad Córdob' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	253	, 'nb_barrio' => 'Ciudad Córdoba' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	254	, 'nb_barrio' => 'Comuneros I' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	255	, 'nb_barrio' => 'Laureano Gómez' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	256	, 'nb_barrio' => 'Mojica' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	257	, 'nb_barrio' => 'Retiro' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	258	, 'nb_barrio' => 'Vallado' , 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	259	, 'nb_barrio' => 'Antonio Nariño' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	260	, 'nb_barrio' => 'Brisas del Limonar' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	261	, 'nb_barrio' => 'Ciudad 2000' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	262	, 'nb_barrio' => 'La Alborada' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	263	, 'nb_barrio' => 'Mariano Ramos' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	264	, 'nb_barrio' => 'Republica de Israel' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	265	, 'nb_barrio' => 'Unión de Vivienda Popular' , 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	266	, 'nb_barrio' => 'Bosques del Limonar' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	267	, 'nb_barrio' => 'Caney' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	268	, 'nb_barrio' => 'Cañaverales' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	269	, 'nb_barrio' => 'Ciudad Campestre' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	270	, 'nb_barrio' => 'Ciudad Capri' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	271	, 'nb_barrio' => 'Ciudad Universitaria' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	272	, 'nb_barrio' => 'Ciudadela Comfandi' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	273	, 'nb_barrio' => 'Ciudadela Paso ancho' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	274	, 'nb_barrio' => 'Club Campestre' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	275	, 'nb_barrio' => 'El Gran Limonar –Cataya' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	276	, 'nb_barrio' => 'El Ingenio' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	277	, 'nb_barrio' => 'El Limonar' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	278	, 'nb_barrio' => 'La Hacienda' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	279	, 'nb_barrio' => 'La Playa' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	280	, 'nb_barrio' => 'La Selva' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	281	, 'nb_barrio' => 'Las Quintas de don Simón' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	282	, 'nb_barrio' => 'Las Vegas' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	283	, 'nb_barrio' => 'Lili' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	284	, 'nb_barrio' => 'Los Portales' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	285	, 'nb_barrio' => 'Los Samanes' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	286	, 'nb_barrio' => 'Mayapan' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	287	, 'nb_barrio' => 'Nuevo Rey' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	288	, 'nb_barrio' => 'Parcelaciones Pance' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	289	, 'nb_barrio' => 'Prados del Limonar' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	290	, 'nb_barrio' => 'Primero de Mayo' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	291	, 'nb_barrio' => 'Santa Anita' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	292	, 'nb_barrio' => 'Unicentro' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	293	, 'nb_barrio' => 'Urbanización Ciudad Jardín' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	294	, 'nb_barrio' => 'Urbanización Rio Lili' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	295	, 'nb_barrio' => 'Urbanización San Joaquín' , 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	296	, 'nb_barrio' => 'Alférez Real' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	297	, 'nb_barrio' => 'Alto Nápoles' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	298	, 'nb_barrio' => 'Buenos Aires' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	299	, 'nb_barrio' => 'Caldas' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	300	, 'nb_barrio' => 'Colinas del Sur' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	301	, 'nb_barrio' => 'Cuarteles de Nápoles' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	302	, 'nb_barrio' => 'El Jordán' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	303	, 'nb_barrio' => 'Farallones' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	304	, 'nb_barrio' => 'Francisco Eladio Ramírez' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	305	, 'nb_barrio' => 'Horizontes' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	306	, 'nb_barrio' => 'Los Chorros' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	307	, 'nb_barrio' => 'Lourdes' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	308	, 'nb_barrio' => 'Mario Correa Rengifo' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	309	, 'nb_barrio' => 'Meléndez' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	310	, 'nb_barrio' => 'Nápoles' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	311	, 'nb_barrio' => 'Prados del Sur' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	312	, 'nb_barrio' => 'Sector Alto Jordán' , 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	313	, 'nb_barrio' => 'Bellavista' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	314	, 'nb_barrio' => 'Cambulos' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	315	, 'nb_barrio' => 'Camino Real Los Fundadores' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	316	, 'nb_barrio' => 'Cañaveralejo' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	317	, 'nb_barrio' => 'Champagnat' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	318	, 'nb_barrio' => 'Cristales' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	319	, 'nb_barrio' => 'Cuarto de Legua' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	320	, 'nb_barrio' => 'El Cedro' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	321	, 'nb_barrio' => 'El Lido' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	322	, 'nb_barrio' => 'El Mortiñal' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	323	, 'nb_barrio' => 'Eucarístico' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	324	, 'nb_barrio' => 'Galindo' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	325	, 'nb_barrio' => 'Guadalupe' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	326	, 'nb_barrio' => 'La Cascada' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	327	, 'nb_barrio' => 'Miraflores' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	328	, 'nb_barrio' => 'Nuevo Tequendama' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	329	, 'nb_barrio' => 'Pampa Linda' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	330	, 'nb_barrio' => 'Plaza de Toros' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	331	, 'nb_barrio' => 'Refugio' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	332	, 'nb_barrio' => 'San Fernando Nuevo' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	333	, 'nb_barrio' => 'San Fernando Viejo' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	334	, 'nb_barrio' => 'Santa Bárbara' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	335	, 'nb_barrio' => 'Santa Isabel' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	336	, 'nb_barrio' => 'Sector Altos de Santa Isabel' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	337	, 'nb_barrio' => 'Sector Bosque Municipal' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	338	, 'nb_barrio' => 'Sector CañaveralejoGuadalupe' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	339	, 'nb_barrio' => 'Sector la Patria Cañaveral' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	340	, 'nb_barrio' => 'Tejares' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	341	, 'nb_barrio' => 'Tres de Julio' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	342	, 'nb_barrio' => 'Unidad Dep. Alberto Galindo' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	343	, 'nb_barrio' => 'Unidad Panamericana' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	344	, 'nb_barrio' => 'Unidad Residencial El Coliseo' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	345	, 'nb_barrio' => 'Unidad Res. Santiago de Cali' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	346	, 'nb_barrio' => 'Urbanización Colseguros' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	347	, 'nb_barrio' => 'Urbanización Militar' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	348	, 'nb_barrio' => 'Urbanización Nueva Granada' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	349	, 'nb_barrio' => 'Urbanización Tequendama' , 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	350	, 'nb_barrio' => 'Belén' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	351	, 'nb_barrio' => 'Belisario Caicedo' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	352	, 'nb_barrio' => 'Brisas de Mayo' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	353	, 'nb_barrio' => 'Cementerio Carabineros' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	354	, 'nb_barrio' => 'Cortijo' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	355	, 'nb_barrio' => 'La Sultana' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	356	, 'nb_barrio' => 'Lleras Camargo' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	357	, 'nb_barrio' => 'Pueblo Joven' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	358	, 'nb_barrio' => 'Siloe' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	359	, 'nb_barrio' => 'Tierra Blanca' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	360	, 'nb_barrio' => 'Urbanización Cañaveralejo' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	361	, 'nb_barrio' => 'Urbanización Cortij' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	362	, 'nb_barrio' => 'Urbanización Venezuela.' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	363	, 'nb_barrio' => 'Venezuela' , 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	364	, 'nb_barrio' => 'Calimio Desepaz' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	365	, 'nb_barrio' => 'Ciudad Talanga' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	366	, 'nb_barrio' => 'Ciudadela del Rio-CVC' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	367	, 'nb_barrio' => 'Compartir' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	368	, 'nb_barrio' => 'DesepazInvicali' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	369	, 'nb_barrio' => 'Las Dalias' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	370	, 'nb_barrio' => 'Las Garzas' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	371	, 'nb_barrio' => 'Los Lideres' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	372	, 'nb_barrio' => 'Pizamos 1' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	373	, 'nb_barrio' => 'Pizamos 2' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	374	, 'nb_barrio' => 'PizamosIII' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	375	, 'nb_barrio' => 'Plantan Tto Puerto Mallarino' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	376	, 'nb_barrio' => 'Potrero Grande' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	377	, 'nb_barrio' => 'Remanso' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	378	, 'nb_barrio' => 'Santa Clara' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	379	, 'nb_barrio' => 'Valle Grande' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	380	, 'nb_barrio' => 'Villa Luz' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	381	, 'nb_barrio' => 'Villa mercedes I' , 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	382	, 'nb_barrio' => 'Ciudad Campestre' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	383	, 'nb_barrio' => 'Condominio Miramontes' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	384	, 'nb_barrio' => 'Haciendas de Alferez' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	385	, 'nb_barrio' => 'Jardín de Pance' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	386	, 'nb_barrio' => 'Jockey Club' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	387	, 'nb_barrio' => 'Reamansode Ciudad jardin' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	388	, 'nb_barrio' => 'Urbanización ciudad Jardín' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	389	, 'nb_barrio' => 'Urbanización Rio Lili' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	390	, 'nb_barrio' => 'Verdanza' , 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],

        ]);

            //// php artisan db:seed --class=BarrioSeeder
        
    }
}
