<template>

    <v-row no-gutters> 
        
        <v-col lg="3" md="4" sm="6" xs="12" v-for="(comercio, i) in comerciosFiltered" :key="i">
                
            <app-comercio :comercio="comercio"></app-comercio>

        </v-col>

    </v-row>
    
</template>

<script>

import AppComercio from '~/components/comercio/AppComercio';

export default 
{
    components: { 
        'app-comercio': AppComercio, 
    },
    props:
    {
        filtros:{
            type:       Object,
            default:    () =>  {  return { nombre: null, categoria: null } }
        },
    },
    computed: 
    {
        comerciosFiltered()
        {
            const comercios = [];

            if ( this.filtros.nombre || this.filtros.categoria  )
            {
               if (this.filtros.categoria)
                {
                    for (const comercio of this.comercios) {

                        if(comercio.categoria_id == this.filtros.categoria)
                        {
                           comercios.push(comercio);
                        }
                    }
                }
            }

            return comercios;
        }
    },
    data () 
	{
        return {
            comercios: [
            {
                id: 101,
                tx_foto: 'comer1',
                tx_nombre: "Mollis Inc.",
                tx_direccion: "P.O. Box 178, 3190 Quam Road", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "045-878-8517", 
                nu_valoracion: 1, 
                categoria_id: 1, 
                tx_geo: "85.31855, 103.41385", 
                tx_region: "Antioquia", 
                tx_ciudad: "Turbo"
            }, 
            {
                id: 102,
                tx_foto: 'comer1',
                tx_nombre: "Massa Rutrum ",
                tx_direccion: "Ap #871-7457 Libero Ave", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "012-007-0338", 
                nu_valoracion: 1, 
                categoria_id: 1, 
                tx_geo: "-38.39774, 33.00408", 
                tx_region: "Antioquia", 
                tx_ciudad: "Envigado"
            }, 
            {
                id: 103,
                tx_foto: 'comer2',
                tx_nombre: "Vel Vulputate ",
                tx_direccion: "9904 Integer Avenue", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "065-518-2637", 
                nu_valoracion: 2, 
                categoria_id: 2, 
                tx_geo: "81.07431, 127.76596", 
                tx_region: "Bolívar", 
                tx_ciudad: "Carmen de Bolivar"
            }, 
            {
                id: 104,
                tx_foto: 'comer2',
                tx_nombre: "Dolor Sit ",
                tx_direccion: "1060 Vestibulum St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "012-203-0393", 
                nu_valoracion: 2, 
                categoria_id: 2, 
                tx_geo: "45.86491, -148.28447", 
                tx_region: "BOL", 
                tx_ciudad: "Carmen de Bolivar"
            }, 
            {
                id: 105,
                tx_foto: 'comer3',
                tx_nombre: "Quis LLC",
                tx_direccion: "Ap #719-9673 Vitae Rd.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "064-620-8836", 
                nu_valoracion: 3, 
                categoria_id: 3, 
                tx_geo: "30.57518, -153.54137", 
                tx_region: "Antioquia", 
                tx_ciudad: "Bello"
            }, 
            {
                id: 106,
                tx_foto: 'comer3',
                tx_nombre: "Vitae Associates",
                tx_direccion: "Ap #375-9201 Primis St.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "062-555-6211", 
                nu_valoracion: 3, 
                categoria_id: 3, 
                tx_geo: "-88.68208, -150.69864", 
                tx_region: "ANT", 
                tx_ciudad: "Bello"
            }, 
            {
                id: 107,
                tx_foto: 'comer4',
                tx_nombre: "Tristique Aliquet ",
                tx_direccion: "5571 Consectetuer Avenue", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "032-586-6714", 
                nu_valoracion: 4, 
                categoria_id: 4, 
                tx_geo: "22.99345, -28.92458", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 108,
                tx_foto: 'comer4',
                tx_nombre: "Sed Associates",
                tx_direccion: "Ap #248-4290 Aliquet, Street", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "081-904-4059", 
                nu_valoracion: 4, 
                categoria_id: 4, 
                tx_geo: "75.25674, 81.70246", 
                tx_region: "BOL", 
                tx_ciudad: "Magangué"
            }, 
            {
                id: 109,
                tx_foto: 'comer5',
                tx_nombre: "Posuere Cubilia ",
                tx_direccion: "2089 Ac St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "038-287-8294", 
                nu_valoracion: 5, 
                categoria_id: 5, 
                tx_geo: "63.2827, -146.31288", 
                tx_region: "Antioquia", 
                tx_ciudad: "Turbo"
            }, 
            {
                id: 110,
                tx_foto: 'comer5',
                tx_nombre: "Enim Company",
                tx_direccion: "176-7562 Curae; Avenue", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "028-366-7971", 
                nu_valoracion: 5, 
                categoria_id: 5, 
                tx_geo: "13.96201, -30.06176", 
                tx_region: "Antioquia", 
                tx_ciudad: "Apartadó"
            }, 
            {
                id: 111,
                tx_foto: 'comer6',
                tx_nombre: "Lobortis Quam ",
                tx_direccion: "140-7642 Integer Road", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "040-679-6221", 
                nu_valoracion: 1, 
                categoria_id: 6, 
                tx_geo: "-74.00605, -126.43355", 
                tx_region: "ATL", 
                tx_ciudad: "Soledad"
            }, 
            {
                id: 112,
                tx_foto: 'comer6',
                tx_nombre: "Lectus Convallis ",
                tx_direccion: "P.O. Box 305, 9453 Molestie. Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "070-156-6111", 
                nu_valoracion: 1, 
                categoria_id: 6, 
                tx_geo: "69.59877, -162.32062", 
                tx_region: "ANT", 
                tx_ciudad: "Envigado"
            }, 
            {
                id: 113,
                tx_foto: 'comer7',
                tx_nombre: "Enim Non ",
                tx_direccion: "4200 Auctor Av.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "026-505-3843", 
                nu_valoracion: 2, 
                categoria_id: 7, 
                tx_geo: "-12.32225, 26.85079", 
                tx_region: "ATL", 
                tx_ciudad: "Malambo"
            }, 
            {
                id: 114,
                tx_foto: 'comer7',
                tx_nombre: "Sem Semper ",
                tx_direccion: "P.O. Box 423, 5342 Neque Street", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "027-251-8716", 
                nu_valoracion: 2, 
                categoria_id: 7, 
                tx_geo: "-12.16353, -86.68398", 
                tx_region: "ANT", 
                tx_ciudad: "Medellín"
            }, 
            {
                id: 115,
                tx_foto: 'comer8',
                tx_nombre: "Commodo Ipsum ",
                tx_direccion: "3080 Facilisis Avenue", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "096-520-4294", 
                nu_valoracion: 3, 
                categoria_id: 8, 
                tx_geo: "6.68706, -172.31712", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 116,
                tx_foto: 'comer8',
                tx_nombre: "Suspendisse Non ",
                tx_direccion: "7761 Libero. Rd.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "052-625-9022", 
                nu_valoracion: 3, 
                categoria_id: 8, 
                tx_geo: "67.08401, -33.27437", 
                tx_region: "Atlántico", 
                tx_ciudad: "Soledad"
            }, 
            {
                id: 117,
                tx_foto: 'comer1',
                tx_nombre: "Vel Quam ",
                tx_direccion: "1647 Parturient Ave", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "027-246-5043", 
                nu_valoracion: 4, 
                categoria_id: 1, 
                tx_geo: "-15.34284, -3.06647", 
                tx_region: "Atlántico", 
                tx_ciudad: "Malambo"
            }, 
            {
                id: 118,
                tx_foto: 'comer1',
                tx_nombre: "Massa LLC",
                tx_direccion: "P.O. Box 747, 8204 Euismod St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "029-998-8460", 
                nu_valoracion: 4, 
                categoria_id: 1, 
                tx_geo: "55.14298, -140.39495", 
                tx_region: "BOL", 
                tx_ciudad: "Magangué"
            }, 
            {
                id: 119,
                tx_foto: 'comer2',
                tx_nombre: "Mauris Company",
                tx_direccion: "829-9084 Ornare St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "043-599-4588", 
                nu_valoracion: 5, 
                categoria_id: 2, 
                tx_geo: "-83.21551, -21.94902", 
                tx_region: "Antioquia", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 120,
                tx_foto: 'comer2',
                tx_nombre: "Torquent Per ",
                tx_direccion: "P.O. Box 118, 8828 Eu Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "041-280-8115", 
                nu_valoracion: 5, 
                categoria_id: 2, 
                tx_geo: "66.69318, 51.32559", 
                tx_region: "ATL", 
                tx_ciudad: "Barranquilla"
            }, 
            {
                id: 121,
                tx_foto: 'comer3',
                tx_nombre: "Erat Volutpat ",
                tx_direccion: "8466 Magna. Rd.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "077-024-1150", 
                nu_valoracion: 1, 
                categoria_id: 3, 
                tx_geo: "2.53063, -31.98519", 
                tx_region: "ANT", 
                tx_ciudad: "Envigado"
            }, 
            {
                id: 122,
                tx_foto: 'comer3',
                tx_nombre: "Eu Odio ",
                tx_direccion: "Ap #546-1438 Auctor. St.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "047-150-4916", 
                nu_valoracion: 1, 
                categoria_id: 3, 
                tx_geo: "3.46772, 14.45649", 
                tx_region: "ANT", 
                tx_ciudad: "Rionegro"
            }, 
            {
                id: 123,
                tx_foto: 'comer4',
                tx_nombre: "Molestie Dapibus ",
                tx_direccion: "913-6646 Ridiculus Rd.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "049-494-7002", 
                nu_valoracion: 2, 
                categoria_id: 4, 
                tx_geo: "-26.73888, 94.84159", 
                tx_region: "Atlántico", 
                tx_ciudad: "Barranquilla"
            }, 
            {
                id: 124,
                tx_foto: 'comer4',
                tx_nombre: "Nec Mauris ",
                tx_direccion: "8194 Eleifend Avenue", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "046-508-8581", 
                nu_valoracion: 2, 
                categoria_id: 4, 
                tx_geo: "-4.04261, -47.16548", 
                tx_region: "Bolívar", 
                tx_ciudad: "Magangué"
            }, 
            {
                id: 125,
                tx_foto: 'comer5',
                tx_nombre: "Consectetuer Rhoncus ",
                tx_direccion: "7394 Donec Street", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "028-535-7335", 
                nu_valoracion: 3, 
                categoria_id: 5, 
                tx_geo: "-62.73637, 147.69529", 
                tx_region: "MAG", 
                tx_ciudad: "Santa Marta"
            }, 
            {
                id: 126,
                tx_foto: 'comer5',
                tx_nombre: "Vulputate Nisi ",
                tx_direccion: "2461 Ultrices St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "004-892-8465", 
                nu_valoracion: 3, 
                categoria_id: 5, 
                tx_geo: "-81.13458, -122.03809", 
                tx_region: "BOL", 
                tx_ciudad: "Carmen de Bolivar"
            }, 
            {
                id: 127,
                tx_foto: 'comer6',
                tx_nombre: "Arcu LLP",
                tx_direccion: "P.O. Box 563, 2667 Massa. Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "071-067-2077", 
                nu_valoracion: 4, 
                categoria_id: 6, 
                tx_geo: "31.47945, -98.23375", 
                tx_region: "ANT", 
                tx_ciudad: "Apartadó"
            }, 
            {
                id: 128,
                tx_foto: 'comer6',
                tx_nombre: "Proin Non ",
                tx_direccion: "Ap #117-9675 Mauris Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "080-032-7112", 
                nu_valoracion: 4, 
                categoria_id: 6, 
                tx_geo: "7.82101, -125.69421", 
                tx_region: "Bolívar", 
                tx_ciudad: "Carmen de Bolivar"
            }, 
            {
                id: 129,
                tx_foto: 'comer7',
                tx_nombre: "Iaculis Inc.",
                tx_direccion: "P.O. Box 287, 1674 Augue, Av.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "032-587-8777", 
                nu_valoracion: 5, 
                categoria_id: 7, 
                tx_geo: "86.20291, 109.6201", 
                tx_region: "Bolívar", 
                tx_ciudad: "Carmen de Bolivar"
            }, 
            {
                id: 130,
                tx_foto: 'comer7',
                tx_nombre: "Ac Eleifend ",
                tx_direccion: "Ap #598-1702 Sollicitudin Road", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "026-746-9216", 
                nu_valoracion: 5, 
                categoria_id: 7, 
                tx_geo: "-23.28591, 90.33709", 
                tx_region: "Antioquia", 
                tx_ciudad: "Envigado"
            }, 
            {
                id: 131,
                tx_foto: 'comer8',
                tx_nombre: "In Scelerisque ",
                tx_direccion: "390-8938 Primis Street", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "049-301-6865", 
                nu_valoracion: 1, 
                categoria_id: 8, 
                tx_geo: "-30.55549, -50.80198", 
                tx_region: "ANT", 
                tx_ciudad: "Apartadó"
            }, 
            {
                id: 132,
                tx_foto: 'comer8',
                tx_nombre: "Quisque Nonummy ",
                tx_direccion: "P.O. Box 434, 4536 Sociis Av.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "077-380-9310", 
                nu_valoracion: 1, 
                categoria_id: 8, 
                tx_geo: "-78.34426, -164.89773", 
                tx_region: "BOL", 
                tx_ciudad: "Cartagena"
            }, 
            {
                id: 133,
                tx_foto: 'comer1',
                tx_nombre: "Tempor Lorem ",
                tx_direccion: "P.O. Box 685, 3327 Sit Avenue", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "028-230-3590", 
                nu_valoracion: 2, 
                categoria_id: 1, 
                tx_geo: "60.64654, 122.92697", 
                tx_region: "Antioquia", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 134,
                tx_foto: 'comer1',
                tx_nombre: "Varius Nam ",
                tx_direccion: "173-8140 Vel St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "052-840-3702", 
                nu_valoracion: 2, 
                categoria_id: 1, 
                tx_geo: "26.57051, 71.34549", 
                tx_region: "ATL", 
                tx_ciudad: "Sabanalarga"
            }, 
            {
                id: 135,
                tx_foto: 'comer2',
                tx_nombre: "Urna Corp.",
                tx_direccion: "Ap #752-2054 Ut Av.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "050-108-7729", 
                nu_valoracion: 3, 
                categoria_id: 2, 
                tx_geo: "33.73269, -51.976", 
                tx_region: "Antioquia", 
                tx_ciudad: "Turbo"
            }, 
            {
                id: 136,
                tx_foto: 'comer2',
                tx_nombre: "Lacinia Sed ",
                tx_direccion: "P.O. Box 988, 6537 Gravida Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "074-193-3190", 
                nu_valoracion: 3, 
                categoria_id: 2, 
                tx_geo: "73.30672, 177.00604", 
                tx_region: "ATL", 
                tx_ciudad: "Sabanalarga"
            }, 
            {
                id: 137,
                tx_foto: 'comer3',
                tx_nombre: "Imperdiet Dictum ",
                tx_direccion: "220-8883 Bibendum Rd.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "051-868-4835", 
                nu_valoracion: 4, 
                categoria_id: 3, 
                tx_geo: "-36.1533, 168.44539", 
                tx_region: "Nariño", 
                tx_ciudad: "Ipiales"
            }, 
            {
                id: 138,
                tx_foto: 'comer3',
                tx_nombre: "Urna Nullam ",
                tx_direccion: "157-3637 Laoreet Rd.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "092-039-2045", 
                nu_valoracion: 4, 
                categoria_id: 3, 
                tx_geo: "76.53657, 53.65691", 
                tx_region: "Antioquia", 
                tx_ciudad: "Turbo"
            }, 
            {
                id: 139,
                tx_foto: 'comer4',
                tx_nombre: "Orci Lacus ",
                tx_direccion: "Ap #733-3062 Magna. Street", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "085-123-3711", 
                nu_valoracion: 5, 
                categoria_id: 4, 
                tx_geo: "51.09136, -77.88678", 
                tx_region: "Antioquia", 
                tx_ciudad: "Envigado"
            }, 
            {
                id: 140,
                tx_foto: 'comer4',
                tx_nombre: "Morbi Incorporated",
                tx_direccion: "Ap #861-7194 Leo. Avenue", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "072-924-3300", 
                nu_valoracion: 5, 
                categoria_id: 4, 
                tx_geo: "-66.66439, -114.27452", 
                tx_region: "Antioquia", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 141,
                tx_foto: 'comer5',
                tx_nombre: "Amet Risus ",
                tx_direccion: "7290 Neque St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "073-333-7597", 
                nu_valoracion: 1, 
                categoria_id: 5, 
                tx_geo: "-87.15445, 97.84869", 
                tx_region: "ANT", 
                tx_ciudad: "Turbo"
            }, 
            {
                id: 142,
                tx_foto: 'comer5',
                tx_nombre: "In Faucibus ",
                tx_direccion: "P.O. Box 592, 4814 In St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "091-546-2544", 
                nu_valoracion: 1, 
                categoria_id: 5, 
                tx_geo: "16.78232, 173.17026", 
                tx_region: "Atlántico", 
                tx_ciudad: "Barranquilla"
            }, 
            {
                id: 143,
                tx_foto: 'comer6',
                tx_nombre: "Fermentum Institute",
                tx_direccion: "7390 Lobortis. Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "087-816-9259", 
                nu_valoracion: 2, 
                categoria_id: 6, 
                tx_geo: "-62.87634, 20.66351", 
                tx_region: "Antioquia", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 144,
                tx_foto: 'comer6',
                tx_nombre: "Egestas Lacinia ",
                tx_direccion: "Ap #793-4464 Ultrices Avenue", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "040-156-3453", 
                nu_valoracion: 2, 
                categoria_id: 6, 
                tx_geo: "69.57265, 1.66148", 
                tx_region: "BOL", 
                tx_ciudad: "Cartagena"
            }, 
            {
                id: 145,
                tx_foto: 'comer7',
                tx_nombre: "Non Inc.",
                tx_direccion: "P.O. Box 383, 7867 Facilisis Road", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "058-650-2041", 
                nu_valoracion: 3, 
                categoria_id: 7, 
                tx_geo: "23.96567, 54.78437", 
                tx_region: "ATL", 
                tx_ciudad: "Sabanalarga"
            }, 
            {
                id: 146,
                tx_foto: 'comer7',
                tx_nombre: "Vel Sapien ",
                tx_direccion: "P.O. Box 205, 3420 Tortor. Road", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "067-376-7730", 
                nu_valoracion: 3, 
                categoria_id: 7, 
                tx_geo: "24.00764, -146.52127", 
                tx_region: "Bolívar", 
                tx_ciudad: "Magangué"
            }, 
            {
                id: 147,
                tx_foto: 'comer8',
                tx_nombre: "Odio Corp.",
                tx_direccion: "Ap #942-6179 Non Road", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "065-714-9376", 
                nu_valoracion: 4, 
                categoria_id: 8, 
                tx_geo: "6.36247, 76.40326", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            }, 
            {
                id: 148,
                tx_foto: 'comer8',
                tx_nombre: "Nunc Lectus ",
                tx_direccion: "P.O. Box 372, 1529 Pellentesque Street", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "060-130-3196", 
                nu_valoracion: 4, 
                categoria_id: 8, 
                tx_geo: "-1.94684, 94.4346", 
                tx_region: "Atlántico", 
                tx_ciudad: "Barranquilla"
            }, 
            {
                id: 149,
                tx_foto: 'comer1',
                tx_nombre: "Sagittis Augue ",
                tx_direccion: "P.O. Box 916, 8736 Mauris St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "015-672-6689", 
                nu_valoracion: 5, 
                categoria_id: 1, 
                tx_geo: "-45.36209, -84.96277", 
                tx_region: "ANT", 
                tx_ciudad: "Medellín"
            }, 
            {
                id: 150,
                tx_foto: 'comer1',
                tx_nombre: "Ligula Eu ",
                tx_direccion: "Ap #120-464 Semper St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "071-329-9161", 
                nu_valoracion: 5, 
                categoria_id: 1, 
                tx_geo: "26.08673, -68.54613", 
                tx_region: "Antioquia", 
                tx_ciudad: "Medellín"
            }, 
            {
                id: 151,
                tx_foto: 'comer2',
                tx_nombre: "In Dolor ",
                tx_direccion: "Ap #632-8452 Purus Street", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "022-104-0950", 
                nu_valoracion: 1, 
                categoria_id: 2, 
                tx_geo: "31.2296, 21.85171", 
                tx_region: "Atlántico", 
                tx_ciudad: "Sabanalarga"
            }, 
            {
                id: 152,
                tx_foto: 'comer2',
                tx_nombre: "Sollicitudin Orci ",
                tx_direccion: "Ap #620-3454 Praesent Street", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "036-410-4067", 
                nu_valoracion: 1, 
                categoria_id: 2, 
                tx_geo: "18.80867, 15.61334", 
                tx_region: "ATL", 
                tx_ciudad: "Soledad"
            }, 
            {
                id: 153,
                tx_foto: 'comer3',
                tx_nombre: "Odio Phasellus ",
                tx_direccion: "Ap #397-6084 Lorem Street", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "029-431-9040", 
                nu_valoracion: 2, 
                categoria_id: 3, 
                tx_geo: "89.66318, -122.55061", 
                tx_region: "Atlántico", 
                tx_ciudad: "Sabanalarga"
            }, 
            {
                id: 154,
                tx_foto: 'comer3',
                tx_nombre: "Aliquam Arcu ",
                tx_direccion: "P.O. Box 383, 8182 Vel Ave", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "085-060-1631", 
                nu_valoracion: 2, 
                categoria_id: 3, 
                tx_geo: "1.24288, 62.84691", 
                tx_region: "Atlántico", 
                tx_ciudad: "Malambo"
            },
            {   
                id: 155,
                tx_foto: 'comer4',
                tx_nombre: "Dui Cum ",
                tx_direccion: "9816 Dictum St.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "070-962-1899", 
                nu_valoracion: 3, 
                categoria_id: 4, 
                tx_geo: "-20.58353, -107.84001", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 156,
                tx_foto: 'comer4',
                tx_nombre: "Tellus Suspendisse ",
                tx_direccion: "924-4698 Vulputate Ave", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "050-339-4328", 
                nu_valoracion: 3, 
                categoria_id: 4, 
                tx_geo: "75.25724, -150.29619", 
                tx_region: "Arauca", 
                tx_ciudad: "Arauca"
            },
            {   
                id: 157,
                tx_foto: 'comer5',
                tx_nombre: "Convallis In ",
                tx_direccion: "555-3349 Malesuada St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "038-829-7170", 
                nu_valoracion: 4, 
                categoria_id: 5, 
                tx_geo: "84.89094, 165.6116", 
                tx_region: "Arauca", 
                tx_ciudad: "Arauca"
            },
            {   
                id: 158,
                tx_foto: 'comer5',
                tx_nombre: "Augue Ut ",
                tx_direccion: "379-5674 A, Rd.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "026-600-9729", 
                nu_valoracion: 4, 
                categoria_id: 5, 
                tx_geo: "36.10526, -150.6257", 
                tx_region: "ATL", 
                tx_ciudad: "Soledad"
            },
            {   
                id: 159,
                tx_foto: 'comer6',
                tx_nombre: "Nulla Dignissim ",
                tx_direccion: "490-5632 Tellus. Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "005-621-3275", 
                nu_valoracion: 5, 
                categoria_id: 6, 
                tx_geo: "-75.87058, -168.07632", 
                tx_region: "Atlántico", 
                tx_ciudad: "Soledad"
            },
            {   
                id: 160,
                tx_foto: 'comer6',
                tx_nombre: "Venenatis Limited",
                tx_direccion: "9971 Malesuada St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "037-112-3794", 
                nu_valoracion: 5, 
                categoria_id: 6, 
                tx_geo: "-23.67201, -24.00645", 
                tx_region: "ANT", 
                tx_ciudad: "Apartadó"
            },
            {   
                id: 161,
                tx_foto: 'comer7',
                tx_nombre: "In Inc.",
                tx_direccion: "3876 Malesuada St.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "013-826-9080", 
                nu_valoracion: 1, 
                categoria_id: 7, 
                tx_geo: "53.05507, -160.09387", 
                tx_region: "ATL", 
                tx_ciudad: "Sabanalarga"
            },
            {   
                id: 162,
                tx_foto: 'comer7',
                tx_nombre: "Vulputate Incorporated",
                tx_direccion: "142-6600 Phasellus Avenue", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "026-732-0067", 
                nu_valoracion: 1, 
                categoria_id: 7, 
                tx_geo: "-16.80147, -86.48843", 
                tx_region: "Antioquia", 
                tx_ciudad: "Turbo"
            },
            {   
                id: 163,
                tx_foto: 'comer8',
                tx_nombre: "Curabitur Ut ",
                tx_direccion: "P.O. Box 893, 2280 Vulputate, Rd.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "001-356-6116", 
                nu_valoracion: 2, 
                categoria_id: 8, 
                tx_geo: "-66.66468, -64.68294", 
                tx_region: "ANT", 
                tx_ciudad: "Envigado"
            },
            {   
                id: 164,
                tx_foto: 'comer8',
                tx_nombre: "Consectetuer Corporation",
                tx_direccion: "8782 Dictum Avenue", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "065-479-6219", 
                nu_valoracion: 2, 
                categoria_id: 8, 
                tx_geo: "11.35103, -75.16193", 
                tx_region: "Antioquia", 
                tx_ciudad: "Bello"
            },
            {   
                id: 165,
                tx_foto: 'comer1',
                tx_nombre: "Fusce Aliquam ",
                tx_direccion: "P.O. Box 118, 6441 Egestas. Street", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "062-500-8251", 
                nu_valoracion: 3, 
                categoria_id: 1, 
                tx_geo: "29.13968, 131.67126", 
                tx_region: "Bolívar", 
                tx_ciudad: "Cartagena"
            },
            {   
                id: 166,
                tx_foto: 'comer1',
                tx_nombre: "Eu Accumsan ",
                tx_direccion: "P.O. Box 927, 1279 Facilisis. Rd.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "040-878-7543", 
                nu_valoracion: 3, 
                categoria_id: 1, 
                tx_geo: "81.15461, -161.83714", 
                tx_region: "Antioquia", 
                tx_ciudad: "Envigado"
            },
            {   
                id: 167,
                tx_foto: 'comer2',
                tx_nombre: "Mus Proin ",
                tx_direccion: "Ap #735-5334 Mauris St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "069-609-5127", 
                nu_valoracion: 4, 
                categoria_id: 2, 
                tx_geo: "83.01953, 89.6045", 
                tx_region: "ANT", 
                tx_ciudad: "Apartadó"
            },
            {   
                id: 168,
                tx_foto: 'comer2',
                tx_nombre: "Vitae Nibh ",
                tx_direccion: "Ap #490-2825 Sociis St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "048-171-6504", 
                nu_valoracion: 4, 
                categoria_id: 2, 
                tx_geo: "58.84837, -102.64846", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 169,
                tx_foto: 'comer3',
                tx_nombre: "Enim Etiam ",
                tx_direccion: "665-6607 Est. Street", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "045-811-9307", 
                nu_valoracion: 5, 
                categoria_id: 3, 
                tx_geo: "-79.54107, 88.62489", 
                tx_region: "BOY", 
                tx_ciudad: "Duitama"
            },
            {   
                id: 170,
                tx_foto: 'comer3',
                tx_nombre: "Vel Pede ",
                tx_direccion: "P.O. Box 517, 5207 Rutrum St.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "063-750-8968", 
                nu_valoracion: 5, 
                categoria_id: 3, 
                tx_geo: "17.51949, -117.09938", 
                tx_region: "ANT", 
                tx_ciudad: "Apartadó"
            },
            {   
                id: 171,
                tx_foto: 'comer4',
                tx_nombre: "Aliquet Lobortis ",
                tx_direccion: "Ap #457-6643 Massa. St.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "014-598-2263", 
                nu_valoracion: 1, 
                categoria_id: 4, 
                tx_geo: "86.66015, -54.50452", 
                tx_region: "Antioquia", 
                tx_ciudad: "Rionegro"
            },
            {   
                id: 172,
                tx_foto: 'comer4',
                tx_nombre: "Eu Institute",
                tx_direccion: "1420 Ultricies St.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "049-749-9059", 
                nu_valoracion: 1, 
                categoria_id: 4, 
                tx_geo: "-34.61844, 11.66323", 
                tx_region: "Antioquia", 
                tx_ciudad: "Apartadó"
            },
            {   
                id: 173,
                tx_foto: 'comer5',
                tx_nombre: "Dis Company",
                tx_direccion: "P.O. Box 264, 7451 Donec St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "020-594-2121", 
                nu_valoracion: 2, 
                categoria_id: 5, 
                tx_geo: "19.3455, -118.69204", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 174,
                tx_foto: 'comer5',
                tx_nombre: "Nulla Eget ",
                tx_direccion: "6640 Mauris Rd.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "027-685-3754", 
                nu_valoracion: 2, 
                categoria_id: 5, 
                tx_geo: "-38.55623, -16.02977", 
                tx_region: "ANT", 
                tx_ciudad: "Turbo"
            },
            {   
                id: 175,
                tx_foto: 'comer6',
                tx_nombre: "Ligula Aenean ",
                tx_direccion: "P.O. Box 962, 3585 Pellentesque St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "069-368-7364", 
                nu_valoracion: 3, 
                categoria_id: 6, 
                tx_geo: "-32.54425, 121.21739", 
                tx_region: "ATL", 
                tx_ciudad: "Barranquilla"
            },
            {   
                id: 176,
                tx_foto: 'comer6',
                tx_nombre: "Vel Est ",
                tx_direccion: "P.O. Box 161, 293 Suspendisse St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "030-171-3419", 
                nu_valoracion: 3, 
                categoria_id: 6, 
                tx_geo: "-41.3871, -149.11659", 
                tx_region: "ANT", 
                tx_ciudad: "Rionegro"
            },
            {   
                id: 177,
                tx_foto: 'comer7',
                tx_nombre: "In LLP",
                tx_direccion: "Ap #267-3087 Tincidunt, Avenue", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "029-514-3585", 
                nu_valoracion: 4, 
                categoria_id: 7, 
                tx_geo: "-9.82434, 30.05308", 
                tx_region: "Antioquia", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 178,
                tx_foto: 'comer7',
                tx_nombre: "Tristique Senectus ",
                tx_direccion: "634-7958 Orci. Rd.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "035-483-3948", 
                nu_valoracion: 4, 
                categoria_id: 7, 
                tx_geo: "-70.46429, 176.59657", 
                tx_region: "Bolívar", 
                tx_ciudad: "Carmen de Bolivar"
            },
            {   
                id: 179,
                tx_foto: 'comer8',
                tx_nombre: "Tempus Eu ",
                tx_direccion: "8392 Tortor Av.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "081-486-0338", 
                nu_valoracion: 5, 
                categoria_id: 8, 
                tx_geo: "-74.0238, 17.76851", 
                tx_region: "Antioquia", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 180,
                tx_foto: 'comer8',
                tx_nombre: "Proin Limited",
                tx_direccion: "Ap #232-7801 Tristique Av.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "061-300-9946", 
                nu_valoracion: 5, 
                categoria_id: 8, 
                tx_geo: "6.149, 38.61999", 
                tx_region: "ANT", 
                tx_ciudad: "Rionegro"
            },
            {   
                id: 181,
                tx_foto: 'comer1',
                tx_nombre: "Rhoncus Donec ",
                tx_direccion: "6907 Sit Av.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "053-574-7167", 
                nu_valoracion: 1, 
                categoria_id: 1, 
                tx_geo: "8.35952, -133.2409", 
                tx_region: "Antioquia", 
                tx_ciudad: "Rionegro"
            },
            {   
                id: 182,
                tx_foto: 'comer1',
                tx_nombre: "Magna Phasellus ",
                tx_direccion: "P.O. Box 184, 5268 Nec, Rd.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "067-243-8709", 
                nu_valoracion: 1, 
                categoria_id: 1, 
                tx_geo: "-60.74034, -107.67653", 
                tx_region: "BOL", 
                tx_ciudad: "Cartagena"
            },
            {   
                id: 183,
                tx_foto: 'comer2',
                tx_nombre: "Vehicula PC",
                tx_direccion: "P.O. Box 307, 8890 Quisque Ave", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "007-985-1621", 
                nu_valoracion: 2, 
                categoria_id: 2, 
                tx_geo: "-17.91321, 28.458", 
                tx_region: "Atlántico", 
                tx_ciudad: "Barranquilla"
            },
            {   
                id: 184,
                tx_foto: 'comer2',
                tx_nombre: "Bibendum Donec ",
                tx_direccion: "Ap #377-5531 Non Rd.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "058-976-5329", 
                nu_valoracion: 2, 
                categoria_id: 2, 
                tx_geo: "-16.59715, 50.72023", 
                tx_region: "ANT", 
                tx_ciudad: "Rionegro"
            },
            {   
                id: 185,
                tx_foto: 'comer3',
                tx_nombre: "Nec PC",
                tx_direccion: "672-7085 Facilisi. Road", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "064-471-8144", 
                nu_valoracion: 3, 
                categoria_id: 3, 
                tx_geo: "-13.13852, 102.07154", 
                tx_region: "ATL", 
                tx_ciudad: "Soledad"
            },
            {   
                id: 186,
                tx_foto: 'comer3',
                tx_nombre: "Egestas Sed ",
                tx_direccion: "P.O. Box 664, 2534 Ac, Rd.", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "008-703-0744", 
                nu_valoracion: 3, 
                categoria_id: 3, 
                tx_geo: "14.5207, 35.55732", 
                tx_region: "Bolívar", 
                tx_ciudad: "Cartagena"
            },
            {   
                id: 187,
                tx_foto: 'comer4',
                tx_nombre: "Curabitur Consequat ",
                tx_direccion: "P.O. Box 256, 3520 Nec St.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "020-101-5518", 
                nu_valoracion: 4, 
                categoria_id: 4, 
                tx_geo: "-0.60009, -114.59811", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 188,
                tx_foto: 'comer4',
                tx_nombre: "Ut Tincidunt ",
                tx_direccion: "262-9628 In Rd.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "014-723-9055", 
                nu_valoracion: 4, 
                categoria_id: 4, 
                tx_geo: "33.21558, -175.82896", 
                tx_region: "Bolívar", 
                tx_ciudad: "Magangué"
            },
            {   
                id: 189,
                tx_foto: 'comer5',
                tx_nombre: "Porttitor Eros ",
                tx_direccion: "4730 Id Rd.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "019-106-9038", 
                nu_valoracion: 5, 
                categoria_id: 5, 
                tx_geo: "53.44367, -70.9067", 
                tx_region: "ATL", 
                tx_ciudad: "Barranquilla"
            },
            {   
                id: 190,
                tx_foto: 'comer5',
                tx_nombre: "Porttitor Eros ",
                tx_direccion: "231 Ornare, St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "098-806-9206", 
                nu_valoracion: 5, 
                categoria_id: 5, 
                tx_geo: "76.04794, 67.29724", 
                tx_region: "Atlántico", 
                tx_ciudad: "Barranquilla"
            },
            {   
                id: 191,
                tx_foto: 'comer6',
                tx_nombre: "Nisl LLP",
                tx_direccion: "585-4261 At Street", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "038-830-5609", 
                nu_valoracion: 1, 
                categoria_id: 6, 
                tx_geo: "44.60312, -152.2086", 
                tx_region: "Antioquia", 
                tx_ciudad: "Turbo"
            },
            {   
                id: 192,
                tx_foto: 'comer6',
                tx_nombre: "Turpis Nulla ",
                tx_direccion: "576-2197 Habitant St.", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "040-239-1135", 
                nu_valoracion: 1, 
                categoria_id: 6, 
                tx_geo: "23.75996, 109.02028", 
                tx_region: "Bolívar", 
                tx_ciudad: "Carmen de Bolivar"
            },
            {   
                id: 193,
                tx_foto: 'comer7',
                tx_nombre: "Hendrerit A ",
                tx_direccion: "4503 Lorem Road", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "020-858-2929", 
                nu_valoracion: 2, 
                categoria_id: 7, 
                tx_geo: "71.62181, 127.50557", 
                tx_region: "Atlántico", 
                tx_ciudad: "Malambo"
            },
            {   
                id: 194,
                tx_foto: 'comer7',
                tx_nombre: "Magnis Dis ",
                tx_direccion: "718-2873 Nisl. Road", 
                tx_hora_inicio: "8:00", 
                tx_hora_fin: "19:00", 
                tx_telefono: "068-598-9687", 
                nu_valoracion: 2, 
                categoria_id: 7, 
                tx_geo: "-83.18074, 174.69618", 
                tx_region: "Antioquia", 
                tx_ciudad: "Medellín"
            },
            {   
                id: 195,
                tx_foto: 'comer8',
                tx_nombre: "Mollis Phasellus ",
                tx_direccion: "Ap #563-1655 Ipsum Rd.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "074-211-5068", 
                nu_valoracion: 3, 
                categoria_id: 8, 
                tx_geo: "-47.05666, -14.43241", 
                tx_region: "CAS", 
                tx_ciudad: "Yopal"
            },
            {   
                id: 196,
                tx_foto: 'comer8',
                tx_nombre: "Eleifend Egestas ",
                tx_direccion: "394-6984 Vitae, St.", 
                tx_hora_inicio: "9:00", 
                tx_hora_fin: "20:00", 
                tx_telefono: "065-651-3994", 
                nu_valoracion: 3, 
                categoria_id: 8, 
                tx_geo: "-3.61869, -47.64417", 
                tx_region: "ANT", 
                tx_ciudad: "Turbo"
            },
            {   
                id: 197,
                tx_foto: 'comer1',
                tx_nombre: "Diam Ltd",
                tx_direccion: "506-5277 Nunc Ave", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "047-768-1191", 
                nu_valoracion: 4, 
                categoria_id: 1, 
                tx_geo: "-21.17646, 68.92502", 
                tx_region: "ANT", 
                tx_ciudad: "Medellín"
            },
            {   
                id: 198,
                tx_foto: 'comer1',
                tx_nombre: "Egestas Blandit ",
                tx_direccion: "P.O. Box 798, 8149 Malesuada St.", 
                tx_hora_inicio: "7:00", 
                tx_hora_fin: "18:00", 
                tx_telefono: "041-667-1392", 
                nu_valoracion: 4, 
                categoria_id: 1, 
                tx_geo: "25.44103, 114.71721", 
                tx_region: "ANT", 
                tx_ciudad: "Apartadó"
            },
            {   
                id: 199,
                tx_foto: 'comer2',
                tx_nombre: "Vivamus Institute",
                tx_direccion: "P.O. Box 555, 6839 Elit. Road", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "059-155-1779", 
                nu_valoracion: 5, 
                categoria_id: 2, 
                tx_geo: "58.08383, 116.04057", 
                tx_region: "ANT", 
                tx_ciudad: "Itagüí"
            },
            {   
                id: 200,
                tx_foto: 'comer2',
                tx_nombre: "Nibh Sit ",
                tx_direccion: "Ap #222-343 Rutrum. Road", 
                tx_hora_inicio: "7:30", 
                tx_hora_fin: "18:30", 
                tx_telefono: "050-249-4571", 
                nu_valoracion: 5, 
                categoria_id: 2, 
                tx_geo: "-83.28569, -116.59915", 
                tx_region: "Antioquia", 
                tx_ciudad: "Rionegro"
            } 
        ]
            

        }
    },
}
</script>

